import Head from "next/head";
import { CreateMember } from "../components/createMember";
import Navbar from "../components/navbar";
import { ProposalList } from "../components/proposalList";
import { useData } from "../contexts/dataContext";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { isMember, loading, account } = useData();

  if (loading) {
    return (
      <div className="h-screen w-screen flex justify-center items-center">
        <div className="text-2xl font-bold text-gray-500 d-flex justify-center align-center">
          <div id="space">
            <div className={styles.elogo}>
                  <div className={styles.u1}></div>
                  <div className={styles.u2}></div>
                  <div className={styles.u3}></div>
                  <div className={styles.u4}></div>
                  <div className={styles.ct}></div>
                  <div className={styles.l1}></div>
                  <div className={styles.l4}></div>
            </div>
          </div>
        </div>
      </div>
    );
  }
  if (!account) {
    return (
      <div className="h-screen w-screen flex justify-center items-center">
        <div className="text-2xl font-bold text-gray-500">
          Please connect Metamask Wallet
        </div>
      </div>
    );
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Funding DAO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      {!isMember && <CreateMember />}
      <div className="h-screen w-screen grid justify-center">
        {isMember && <ProposalList />}
      </div>
    </div>
  );
}
