import Head from "next/head";
import { CreateMember } from "../components/createMember";
import Navbar from "../components/navbar";
import Footer from "../components/footer";
import { ProposalList } from "../components/proposalList";
import { useData } from "../contexts/dataContext";
import styles from "../styles/Home.module.css";
import AOS from 'aos';
import 'aos/dist/aos.css'; 
import { useEffect } from "react";
export default function Home() {
  useEffect(() => {
    AOS.init();
  },[])
  const { isMember, loading, account } = useData();

  if (loading) {
    return (
      <div className="h-screen w-screen flex justify-center items-center">
        <div className="text-2xl font-bold text-gray-500 d-flex justify-center align-center">
          <div id="space">
            <div className={styles.elogo}>
                  <div className={styles.u1}></div>
                  <div className={styles.u2}></div>
                  <div className={styles.u3}></div>
                  <div className={styles.u4}></div>
                  <div className={styles.ct}></div>
                  <div className={styles.l1}></div>
                  <div className={styles.l4}></div>
            </div>
          </div>
        </div>
      </div>
    );
  }
  if (!account) {
    return (
      <div className="h-screen w-screen flex justify-center items-center">
        <div className="text-2xl font-bold text-gray-500">
          Please connect Metamask Wallet
        </div>
      </div>
    );
  }
  return (
    <>
    <div className={styles.container}>
      <Head>
        <title>Funding DAO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <div className={styles.home_landing_parent}>
        <div className={styles.first_heading_div}
          data-aos="fade-up"
          data-aos-offset="100"
          data-aos-delay="10"
          data-aos-duration="800"
          data-aos-easing="ease-in-out"
        >
          <span className={styles.first_heading}>Welcome To DeFund</span>
        </div>
        <div className={styles.second_heading_div}
          data-aos="fade-up"
          data-aos-offset="150"
          data-aos-delay="30"
          data-aos-duration="800"
          data-aos-easing="ease-in-out"
        >
          <span className={styles.second_heading}>The Future of Funding</span>
        </div>
        <div className={styles.para_span_div}
        >
          <div className="grid grid-cols-2 max-w-9xl justify-center">
            <div className="p-5 flex justify-center align-center"
              data-aos="fade-up"
              data-aos-offset="200"
              data-aos-delay="50"
              data-aos-duration="800"
              data-aos-easing="ease-in-out"
            >
              <img src="/img1.png" alt="" style={{width:"50%"}}/>
            </div>
            <div className="p-5"
              data-aos="fade-up"
              data-aos-offset="200"
              data-aos-delay="50"
              data-aos-duration="800"
              data-aos-easing="ease-in-out"
            >
                <h1 className="text-xl my-2" style={{"color":"#fff"}}>Who Are We?</h1>
                <span className={styles.para_span}>
                  We are DeFund a Decentralized Autonomous Organization(DAO) , and we assist you in managing your funds. You can create a fund proposal and manage it using DeFund from any location in the world. Our interactive, user-friendly interface makes it easy for you to manage your organization's funding from any location at any time. Our main priority is to manage all of your financial tasks and records. We have a decentralised blockchain that is powered by the Ethereum blockchain that updates all the participants and members continuously.
                </span>
            </div>
          </div>
        </div>
      </div>
      <div className={styles.first_div_parent}>
        <div className={styles.fdiv_heading_div}>
          DAO Triangle
        </div>
        <div className="grid grid-cols-3 max-w-9xl justify-center">
          <div className={styles.fdiv_card_parent}
            // data-aos="fade-up"
            // data-aos-offset="200"
            // data-aos-delay="50"
            // data-aos-duration="800"
            // data-aos-easing="ease-in-out"
          >
            <div className={styles.fdiv_card_icon}>
              <img src="/gover.png" alt="" style={{width:"70px"}}/>
            </div>
            <div className={styles.fdiv_card_text}>
                <h2 className="text-lg mb-2">Governance</h2>
                Governance rules cover all aspects of an organization's existence, including its legal framework, membership, mission, operations, and off-chain and on-chain voting.
            </div>
          </div>
          <div className={styles.fdiv_card_parent}
            // data-aos="fade-up"
            // data-aos-offset="200"
            // data-aos-delay="50"
            // data-aos-duration="800"
            // data-aos-easing="ease-in-out"
          >
            <div className={styles.fdiv_card_icon}>
              <img src="/decen.png" alt="" style={{width:"70px"}}/>
            </div>
            <div className={styles.fdiv_card_text}>
                <h2 className="text-lg mb-2">Decentralized</h2>
                Technology and politics are combined in decentralisation to create a belief system that identifies the traits of people who choose to join the DAO. 
            </div>
          </div>
          <div className={styles.fdiv_card_parent}
            // data-aos="fade-up"
            // data-aos-offset="200"
            // data-aos-delay="50"
            // data-aos-duration="800"
            // data-aos-easing="ease-in-out"
          >
            <div className={styles.fdiv_card_icon}>
              <img src="/indi.png" alt="" style={{width:"70px"}} />
            </div>
            <div className={styles.fdiv_card_text}>
                <h2 className="text-lg mb-2">Individual</h2>
                People who are willing to take care of themselves and who believe in self-government and the common good are frequently referred to as individuals.
            </div>
          </div>
        </div>
      </div>
      <div className={styles.timeline_div_parent} style={{marginTop:"50px"}}>
        <div className={styles.fdiv_heading_div}>
          What is DeFund?
        </div>
        <div className="container1">
                <div className="timeline">
                    <div className="timeline-container primary">
                        <div className="timeline-icon flex justify-center">
                            <img src="/interface.png" style={{width:"70%",height:"60%",marginTop:"10px"}}/>
                        </div>
                        <div className="timeline-body">
                            <h4 className="timeline-title"><span className="badge">Interactive User Friendly Interface</span></h4>
                            {/* <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam necessitatibus numquam earum ipsa fugiat veniam suscipit, officiis repudiandae, eum recusandae neque dignissimos. Cum fugit laboriosam culpa, repellendus esse commodi deserunt.</p> */}
                        </div>
                    </div>
                    <div className="timeline-container danger">
                        <div className="timeline-icon flex justify-center">
                          <img src="/member.png" style={{width:"70%",height:"60%",marginTop:"10px"}}/>
                        </div>
                        <div className="timeline-body">
                            <h4 className="timeline-title"><span className="badge">DeFund Members</span></h4>
                            {/* <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam necessitatibus numquam earum ipsa fugiat veniam suscipit, officiis repudiandae, eum recusandae neque dignissimos. Cum fugit laboriosam culpa, repellendus esse commodi deserunt.</p> */}
                        </div>
                    </div>
                    <div className="timeline-container info">
                        <div className="timeline-icon flex justify-center">
                            <img src="/stakeholder.png" style={{width:"70%",height:"60%",marginTop:"10px"}}/>
                        </div>
                        <div className="timeline-body">
                            <h4 className="timeline-title"><span className="badge">DeFund Stakeholders</span></h4>
                            {/* <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam necessitatibus numquam earum ipsa fugiat veniam suscipit, officiis repudiandae, eum recusandae neque dignissimos. Cum fugit laboriosam culpa, repellendus esse commodi deserunt.</p> */}
                        </div>
                    </div>
                    <div className="timeline-container">
                        <div className="timeline-icon flex justify-center">
                          <img src="/records.png" style={{width:"70%",height:"60%",marginTop:"10px"}}/>
                        </div>
                        <div className="timeline-body">
                            <h4 className="timeline-title"><span className="badge">Funds Records Management</span></h4>
                            {/* <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam necessitatibus numquam earum ipsa fugiat veniam suscipit, officiis repudiandae, eum recusandae neque dignissimos. Cum fugit laboriosam culpa, repellendus esse commodi deserunt.</p> */}
                        </div>
                    </div>
                    <div className="timeline-container success">
                        <div className="timeline-icon flex justify-center">
                          <img src="/management.png" style={{width:"70%",height:"60%",marginTop:"10px"}}/>
                        </div>
                        <div className="timeline-body">
                            <h4 className="timeline-title"><span className="badge">Funds Flow Management</span></h4>
                            {/* <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam necessitatibus numquam earum ipsa fugiat veniam suscipit, officiis repudiandae, eum recusandae neque dignissimos. Cum fugit laboriosam culpa, repellendus esse commodi deserunt.</p> */}
                        </div>
                    </div>
                    <div className="timeline-container warning">
                        <div className="timeline-icon flex justify-center">
                        <img src="/updates.png" style={{width:"70%",height:"60%",marginTop:"10px"}}/>
                        </div>
                        <div className="timeline-body">
                            <h4 className="timeline-title"><span className="badge">Regular Updates to Member & Stakeholders</span></h4>
                            {/* <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam necessitatibus numquam earum ipsa fugiat veniam suscipit, officiis repudiandae, eum recusandae neque dignissimos. Cum fugit laboriosam culpa, repellendus esse commodi deserunt.</p> */}
                        </div>
                    </div>
                    <div className="timeline-container">
                        <div className="timeline-icon flex justify-center">
                        <img src="/professional.png" style={{width:"70%",height:"60%",marginTop:"10px"}}/>
                        </div>
                        <div className="timeline-body">
                            <h4 className="timeline-title"><span className="badge">Professional Highly Robust Platform</span></h4>
                            {/* <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam necessitatibus numquam earum ipsa fugiat veniam suscipit, officiis repudiandae, eum recusandae neque dignissimos. Cum fugit laboriosam culpa, repellendus esse commodi deserunt.</p> */}
                        </div>
                    </div>
                    <div className="timeline-container info">
                        <div className="timeline-icon flex justify-center">
                        <img src="/status.png" style={{width:"70%",height:"60%",marginTop:"10px"}}/>
                        </div>
                        <div className="timeline-body">
                            <h4 className="timeline-title"><span className="badge">Organization Funding Status Management</span></h4>
                            {/* <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam necessitatibus numquam earum ipsa fugiat veniam suscipit, officiis repudiandae, eum recusandae neque dignissimos. Cum fugit laboriosam culpa, repellendus esse commodi deserunt.</p> */}
                        </div>
                    </div>
                </div>
        </div>
      </div>
    </div>
    <Footer/>
  
    </>
  );
}
