import Head from "next/head";
import Navbar from "../components/navbar";
import { ProposalInvestmentCard } from "../components/proposalInvestmentCard";
import { useData } from "../contexts/dataContext";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { allInvestedProposal, loading, account } = useData();

  if (loading) {
    return (
      <div className="h-screen w-screen flex justify-center items-center">
        <div className="text-2xl font-bold text-gray-500">Loading...</div>
      </div>
    );
  }
  if (!account) {
    return (
      <div className="h-screen w-screen flex justify-center items-center">
        <div className="text-2xl font-bold text-gray-500">
          Please connect Metamask Wallet
        </div>
      </div>
    );
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Funding DAO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <span className="text-lg font-bold my-5" style={{"color":"#fff"}}>My Investments</span>
      <main className="grid grid-cols-3 max-w-9xl justify-center" style={{"width":"100% !important"}}>
        {allInvestedProposal.length == 0 && (
          <div className="no_proposal_card_parent" style={{"marginTop":"100px"}}>
          <div className="no_pro_card">
            <div className="no_pro_card_icon_div">
              <img src="/alert.png" style={{"height":"100%"}}/>
            </div>
            <div className="no_pro_card_text_div">
            Sorry, you have not voted in any proposals yet.
            </div>
          </div>
        </div>
        )}
        {allInvestedProposal.map((proposal) => (
          <ProposalInvestmentCard
            key={proposal.id}
            proposal={proposal}
            openModal={() => {}}
          />
        ))}
      </main>
    </div>
  );
}
